




// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Author: Javed Kansi
// ______________________________________________________

package uk.co.planetbeyond.managedbean;

import uk.co.planetbeyond.generated.ActivityBean;
import com.sleepycat.persist.model.Persistent;

/**
* If any changes needs to be made to the ActivityBean, it MUST not be made directly to ActivityBean
* Instead the ActivityManagedBean should be used to make the changes
*/
@Persistent
public class ActivityManagedBean extends ActivityBean
{
	private static final long serialVersionUID = 2008238579589192331L;

	/**
	* Make the constructor public so that it can be accessed externally
	*/
	public ActivityManagedBean()
	{
		super();
	}
}
