
// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Author: Javed Kansi
// ______________________________________________________

package uk.co.planetbeyond.manager;

import java.util.Date;

import uk.co.planetbeyond.generated.ActivityBean;
import uk.co.planetbeyond.generated.ActivityManager;
import uk.co.planetbeyond.generated.exception.DAOException;
import uk.co.planetbeyond.managedbean.ActivityManagedBean;

/**
 * If any change needs to be made to the ActivityManager, it MUST not be made directly Instead the ActivityManagerImpl class should be used to make
 * the changes
 */
public class ActivityManagerImpl extends ActivityManager
{
	/**
	 * Singleton instance of this class
	 */
	private static ActivityManagerImpl singleton = new ActivityManagerImpl();

	/**
	 * Make the constructor private to make the class singleton
	 */
	private ActivityManagerImpl()
	{
		super();

		// set the singleton instance of ActivityManagerImpl class in the ActivityManager so that
		// ActivityManager.getInstance() also points to the singleton instance of ActivityManagerImpl
		setInstance(this);
	}

	/**
	 * To make the singleton instance available to external classes
	 */
	public static ActivityManagerImpl getInstance()
	{
		return singleton;
	}

	/**
	 * Override this method so that it returns an instance of ActivityManagedBean instead of ActivityBean
	 */
	@Override
	public ActivityBean createActivityBean()
	{
		return new ActivityManagedBean();
	}

	/**
	 * @param msisdn
	 * @param uniqueId
	 * @param context
	 * @param activityName
	 * @param duration
	 * @param dtmf
	 * @throws DAOException
	 */
	public void saveCallActivity(String msisdn, String uniqueId, String context, String activityName, Integer duration, String dtmf) throws DAOException
	{
		ActivityBean activity = new ActivityBean();
		activity.setMsisdn(msisdn);
		activity.setUniqueId(uniqueId);
		activity.setCreationTimestamp(new Date());
		activity.setContext(context);
		activity.setActivityName(activityName);
		activity.setDuration(duration);
		activity.setDtmf(dtmf);
		activity.save();
	}
}
