




// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Author: Javed Kansi
// ______________________________________________________

package uk.co.planetbeyond.manager;

import uk.co.planetbeyond.generated.ContentManager;
import uk.co.planetbeyond.generated.ContentBean;
import uk.co.planetbeyond.managedbean.ContentManagedBean;

/**
* If any change needs to be made to the ContentManager, it MUST not be made directly
* Instead the ContentManagerImpl class should be used to make the changes
*/
public class ContentManagerImpl extends ContentManager 
{
	/**
	* Singleton instance of this class
	*/
	private static ContentManagerImpl singleton = new ContentManagerImpl();
	
	/**
	* Make the constructor private to make the class singleton
	*/
	private ContentManagerImpl()
	{
		super();
		
		// set the singleton instance of ContentManagerImpl class in the ContentManager so that
		// ContentManager.getInstance() also points to the singleton instance of ContentManagerImpl 
		setInstance(this);
	}
	
	/**
	* To make the singleton instance available to external classes
	*/
	public static ContentManagerImpl getInstance()
	{
		return singleton;
	}

	/**
	* Override this method so that it returns an instance of ContentManagedBean instead of ContentBean
	*/
	@Override
	public ContentBean createContentBean()
	{
		return new ContentManagedBean();
	}   
}
