




// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Author: Javed Kansi
// ______________________________________________________

package uk.co.planetbeyond.manager;

import uk.co.planetbeyond.generated.SegmentReportManager;
import uk.co.planetbeyond.generated.SegmentReportBean;
import uk.co.planetbeyond.managedbean.SegmentReportManagedBean;

/**
* If any change needs to be made to the SegmentReportManager, it MUST not be made directly
* Instead the SegmentReportManagerImpl class should be used to make the changes
*/
public class SegmentReportManagerImpl extends SegmentReportManager 
{
	/**
	* Singleton instance of this class
	*/
	private static SegmentReportManagerImpl singleton = new SegmentReportManagerImpl();
	
	/**
	* Make the constructor private to make the class singleton
	*/
	private SegmentReportManagerImpl()
	{
		super();
		
		// set the singleton instance of SegmentReportManagerImpl class in the SegmentReportManager so that
		// SegmentReportManager.getInstance() also points to the singleton instance of SegmentReportManagerImpl 
		setInstance(this);
	}
	
	/**
	* To make the singleton instance available to external classes
	*/
	public static SegmentReportManagerImpl getInstance()
	{
		return singleton;
	}

	/**
	* Override this method so that it returns an instance of SegmentReportManagedBean instead of SegmentReportBean
	*/
	@Override
	public SegmentReportBean createSegmentReportBean()
	{
		return new SegmentReportManagedBean();
	}   
}
